# ─────────────────────────────────────────────
#  Autostart
# ─────────────────────────────────────────────

# Portal
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP

# Cursor
exec-once = hyprctl setcursor capitaine-cursors 24

# Clock widget
exec-once = qs -c clock

# Wallpaper
exec-once = swaybg -i "/home/user/Downloads/daniel-leone-v7daTKlZzaw-unsplash 1.png" -m fill
