# ─────────────────────────────────────────────
#  Window Rules
# ─────────────────────────────────────────────

# ─── Blur terminal background ───
windowrule = opacity 0.85 0.80, match:class kitty

# ─── Float certain windows ───
windowrule = float on, match:class pavucontrol
windowrule = float on, match:class nm-connection-editor
windowrule = float on, match:class org.gnome.Nautilus

# ─── Layer blur ───
layerrule = blur on, match:namespace fuzzel
layerrule = ignore_alpha 0.3, match:namespace fuzzel

layerrule = blur on, match:namespace quickshell-clock
layerrule = ignore_alpha 0.05, match:namespace quickshell-clock

